In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("VF and clinical information.csv", header=[0, 1])

## Uncleaned dataset

In [3]:
df

,Subject Number,Laterality,Age,Gender,IOP,CCT,Total Visits,Progression Status,Unnamed: 8_level_0,Unnamed: 9_level_0,...,Unnamed: 70_level_0,Unnamed: 71_level_0,Unnamed: 72_level_0,Unnamed: 73_level_0,Unnamed: 74_level_0,Unnamed: 75_level_0,Unnamed: 76_level_0,Unnamed: 77_level_0,Unnamed: 78_level_0,Unnamed: 79_level_0
,Unnamed: 0_level_1,Unnamed: 1_level_1,Unnamed: 2_level_1,Unnamed: 3_level_1,Unnamed: 4_level_1,Unnamed: 5_level_1,Unnamed: 6_level_1,PLR2,PLR3,MD,...,51,52,53,54,55,56,57,58,59,60
0,1,OD,46,F,14.7,535,3,0,0,0,...,20,22,21,23,26,14,13,19,20,21
1,1,OS,46,F,15.3,525,4,0,0,0,...,21,22,21,21,21,23,25,22,25,22
2,2,OS,57,M,15.5,545,3,0,0,0,...,17,20,24,13,-1,-1,-1,-1,-1,23
3,3,OD,41,M,17.0,557,7,1,0,1,...,27,25,16,21,22,23,23,22,26,30
4,4,OS,58,M,14.7,487,4,0,0,0,...,21,22,22,16,24,23,22,12,14,27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
258,142,OS,34,F,20.7,516,6,0,0,0,...,27,24,23,3,3,-1,14,28,27,25
259,143,OD,51,F,9.0,479,4,0,0,0,...,27,27,27,28,27,28,27,26,26,26
260,143,OS,51,F,8.0,477,4,1,0,0,...,21,24,28,28,27,26,24,25,25,22
261,144,OD,21,M,20.0,556,3,0,0,0,...,29,26,24,24,27,26,24,16,23,27
262,144,OS,21,M,18.0,550,3,0,0,1,...,22,24,23,23,26,27,26,23,24,23

In [4]:
df.columns = df.columns.get_level_values(1)

In [5]:
df.columns

Index(['Unnamed: 0_level_1', 'Unnamed: 1_level_1', 'Unnamed: 2_level_1',
       'Unnamed: 3_level_1', 'Unnamed: 4_level_1', 'Unnamed: 5_level_1',
       'Unnamed: 6_level_1', 'PLR2', 'PLR3', 'MD', 'Unnamed: 10_level_1',
       'Mean', 'S', 'N', 'I', 'T', 'Unnamed: 16_level_1',
       'Unnamed: 17_level_1', 'Unnamed: 18_level_1', '0', '1', '2', '3', '4',
       '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17',
       '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29',
       '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41',
       '42', '43', '44', '45', '46', '47', '48', '49', '50', '51', '52', '53',
       '54', '55', '56', '57', '58', '59', '60'],
      dtype='object')

In [6]:
df.columns = ["SUBJECT NUMBER","Laterality"
            ,"AGE","GENDER","IOP","CCT","TOTAL VISITS",
              "PLR2","PLR3","MD","Category of Glaucoma","Mean","S","N","I","T",
              "CFP","DEVICE","Resolution","VF0","VF1","VF2","VF3","VF4","VF5","VF6","VF7","VF8",
              "VF9","VF10","VF11","VF12","VF13","VF14","VF15","VF16","VF17","VF18","VF19","VF20",
              "VF21","VF22","VF23","VF24","VF25","VF26","VF27","VF28","VF29","VF30","VF31","VF32",
              "VF33","VF34","VF35","VF36","VF37","VF38","VF39","VF40","VF41","VF42","VF43","VF44",
              "VF45","VF46","VF47","VF48","VF49","VF50","VF51","VF52","VF53","VF54","VF55","VF56","VF57","VF58","VF59","VF60"]

In [7]:
len(df.columns)

80

## Cleaned Dataset for better Analysis

In [8]:
df.head(10) #first 10 rows

,SUBJECT NUMBER,Laterality,AGE,GENDER,IOP,CCT,TOTAL VISITS,PLR2,PLR3,MD,...,VF51,VF52,VF53,VF54,VF55,VF56,VF57,VF58,VF59,VF60
0,1,OD,46,F,14.7,535,3,0,0,0,...,20,22,21,23,26,14,13,19,20,21
1,1,OS,46,F,15.3,525,4,0,0,0,...,21,22,21,21,21,23,25,22,25,22
2,2,OS,57,M,15.5,545,3,0,0,0,...,17,20,24,13,-1,-1,-1,-1,-1,23
3,3,OD,41,M,17.0,557,7,1,0,1,...,27,25,16,21,22,23,23,22,26,30
4,4,OS,58,M,14.7,487,4,0,0,0,...,21,22,22,16,24,23,22,12,14,27
5,5,OS,59,F,19.0,547,6,0,0,0,...,20,22,23,18,17,23,22,12,13,23
6,6,OD,54,F,13.5,502,4,0,0,0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
7,7,OD,33,F,19.0,534,4,0,0,0,...,20,21,24,23,26,25,12,16,21,20
8,7,OS,33,F,19.0,530,4,0,0,0,...,19,23,25,19,19,5,22,27,13,22
9,8,OD,41,M,13.5,545,6,0,0,1,...,2,11,14,2,-1,-1,-1,-1,-1,8

In [9]:
from IPython.display import Image, display
from IPython.core.display import HTML

In [10]:
df_10 = df.head(10)

In [11]:
df_10

,SUBJECT NUMBER,Laterality,AGE,GENDER,IOP,CCT,TOTAL VISITS,PLR2,PLR3,MD,...,VF51,VF52,VF53,VF54,VF55,VF56,VF57,VF58,VF59,VF60
0,1,OD,46,F,14.7,535,3,0,0,0,...,20,22,21,23,26,14,13,19,20,21
1,1,OS,46,F,15.3,525,4,0,0,0,...,21,22,21,21,21,23,25,22,25,22
2,2,OS,57,M,15.5,545,3,0,0,0,...,17,20,24,13,-1,-1,-1,-1,-1,23
3,3,OD,41,M,17.0,557,7,1,0,1,...,27,25,16,21,22,23,23,22,26,30
4,4,OS,58,M,14.7,487,4,0,0,0,...,21,22,22,16,24,23,22,12,14,27
5,5,OS,59,F,19.0,547,6,0,0,0,...,20,22,23,18,17,23,22,12,13,23
6,6,OD,54,F,13.5,502,4,0,0,0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
7,7,OD,33,F,19.0,534,4,0,0,0,...,20,21,24,23,26,25,12,16,21,20
8,7,OS,33,F,19.0,530,4,0,0,0,...,19,23,25,19,19,5,22,27,13,22
9,8,OD,41,M,13.5,545,6,0,0,1,...,2,11,14,2,-1,-1,-1,-1,-1,8

In [12]:
def add_image_html_tag(image_url: str, width: int = 500) -> str:
    return f'<img src="{image_url}" width="{width}">'
df_10_copy = df_10.copy()
df_10_copy.loc[:, "CFP"] = df_10_copy["CFP"].apply(add_image_html_tag)
from IPython.display import HTML
HTML(df_10_copy.to_html(escape=False))

In [13]:
df.to_csv("cleaned_dataset_Glaucoma.csv", index=False)